services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: ts-proxy
    env_file: .env
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      # - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /root/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  proxy:
    image: ghcr.io/vpavin/nginx-stream:main
    depends_on:
      - tailscale
    volumes:
      - /root/nginx/proxy.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    network_mode: service:tailscale
  gateway:
    image: ghcr.io/vpavin/nginx-stream:main
    depends_on:
      - proxy
    ports:
      - "8211:8211/udp"
    volumes:
      - /root/nginx/gateway.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
